### ISSUE TITLE
Upload on Huggingface

### ISSUE THREAD

**Issue by maxtrem** [AI21Labs/sense-bert#3]
Hey,

A very interesting paper, thanks a lot for this contribution!
Do you have plans to upload a model on huggingface?

Best,
Max

**Comment by oriram** [comment]
Hi @maxtrem, Thanks for your interest!
Unfortunately, we're not planning to upload our model to HuggingFace at the moment.

**Comment by maxtrem** [comment]
@oriram Too bad, but thanks for the reply!
